=== hY43/Acorn/MyBatis/20160803/web/WebContent/20160802/xml05.dtd
<?xml version="1.0" encoding="UTF-8"?>

	<!ELEMENT department (dept)+> 
	<!--
	default : 1번만 사용
	+ : 1개 이상 
	* : 0개 이상
	? : 0 또는 1개
	A|B : A 또는 B 둘 중에 하나만 가능
	() : 요소를 그룹으로 선언하여 정의
	-->
	<!ELEMENT dept (deptno, dname, loc)>
	<!ELEMENT deptno (#PCDATA)>
	<!ELEMENT dname (#PCDATA)>
	<!ELEMENT loc (#PCDATA)>

=== hY43/Acorn/05_XML&MyBatis/01_web/WebContent/20160802/xml05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE department[
	<!ELEMENT department (dept)+> 
	<!--
	default : 1번만 사용
	+ : 1개 이상 
	* : 0개 이상
	? : 0 또는 1개
	A|B : A 또는 B 둘 중에 하나만 가능
	() : 요소를 그룹으로 선언하여 정의
	-->
	<!ELEMENT dept (deptno, dname, loc)>
	<!ELEMENT deptno (#PCDATA)>
	<!ELEMENT dname (#PCDATA)>
	<!ELEMENT loc (#PCDATA)>
]>
<!-- 위의 사항을 DTD 파일로 만들어 아래와 같이 관리할 수 있다. 
SYSTEM: 사용자 정의
PUBLIC: FRAMEWORK
-->
<!-- <!DOCTYPE department SYSTEM "xml05.dtd" > -->
<department>
	<dept>
		<deptno>10</deptno>
		<dname>sales</dname>
		<loc>DALLAS</loc>
	</dept>
	<dept>
		<deptno>20</deptno>
		<dname>research</dname>
		<loc>NEW YORK</loc>
	</dept>
</department>
