=== hY43/Acorn/05_XML&MyBatis/01_web/WebContent/20160802/hw.dtd
<?xml version="1.0" encoding="UTF-8"?>

	<!ELEMENT employee (emp)+ >
	<!ELEMENT emp (empno, ename, sal, addrs*, deptno) >
	<!ELEMENT empno (#PCDATA) >
	<!ELEMENT ename (#PCDATA) >
	<!ELEMENT sal (#PCDATA) >
	<!ELEMENT addrs (#PCDATA) >
	<!ELEMENT deptno (#PCDATA) >
	
	<!ATTLIST emp age CDATA #IMPLIED >
	<!ATTLIST empno grade (A|B|C|D|F) "F" >
	<!ATTLIST addrs loc CDATA #IMPLIED >

=== hY43/Acorn/05_XML&MyBatis/01_web/WebContent/20160802/hw.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE employee SYSTEM "hw.dtd" > 

<!-- grade는 ABCD 중 1개 기본 값은 F -->
<employee>
	<emp age="22">
		<empno grade="A">7788</empno> 
		<ename>scott</ename>
		<sal>3000</sal>
		<addrs loc="USA">DALLAS</addrs>
		<addrs loc="KOREA">SEOUL</addrs>
		<deptno>10</deptno>
	</emp>
	<emp age="33">
		<empno grade="B">7799</empno>
		<ename>SMITH</ename>
		<sal>1650</sal>
		<deptno>20</deptno>
	</emp>
</employee>
